@host=http://localhost:5209
@userId=6686667a-a278-47f5-81c8-968762602d44
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF5byIsImZhbWlseV9uYW1lIjoiSFIiLCJlbWFpbCI6Im1heW9ockBtYXlvaHIuY29tIiwiaWQiOiI2Njg2NjY3YS1hMjc4LTQ3ZjUtODFjOC05Njg3NjI2MDJkNDQiLCJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sInJvbGVzIjoicmFuZG9tUm9sZSIsImV4cCI6MTc0MjIwNzE5MCwiaXNzIjoiR3ltTWFuYWdlbWVudCIsImF1ZCI6Ikd5bU1hbmFnZW1lbnQifQ.Erpa42LMwH6CKNG80Hext2IQh607csIB8uhp8Uff_TQ

### Admin
POST {{host}}/users/{{userId}}/profiles/admin
Authorization: Bearer {{token}}

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer

### Participant
POST {{host}}/users/{{userId}}/profiles/participant