@host=http://localhost:5209
@adminId=7778561A-09E9-48C9-B862-D5F42FEC0CBE

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Pro",
    "AdminId": "{{adminId}}"
}

