@host=http://localhost:5209
@subscriptionId=5E3CEDD5-8EB8-4757-BA95-2D43C4BA41C8
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF5byIsImZhbWlseV9uYW1lIjoiSFIiLCJlbWFpbCI6Im1heW9ockBtYXlvaHIuY29tIiwiaWQiOiJkODQxNmMzYS01NzU2LTQyMDQtYjUxYi1kYjIwOTM5MWFmYmEiLCJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluSWQiOiI3ODU3NmNlOC1mMTcyLTQ0N2EtOWEyNS01NjlhMjA1YjBjZDciLCJyb2xlcyI6WyJyYW5kb21Sb2xlIiwiQWRtaW4iXSwiZXhwIjoxNzQxNTkwODc0LCJpc3MiOiJHeW1NYW5hZ2VtZW50IiwiYXVkIjoiR3ltTWFuYWdlbWVudCJ9.3fCSnTD9CINbcPHX6dxB8x85qwvlHEcysgbCM84PyKc

POST {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "MayoHrGym"
}

###

http://localhost:5051/subscriptions/51b5d6fd-75fe-44d9-a56f-2dcde66fad56/gyms/59bf64b3-fee6-4403-9631-d1a4f57cb032