@host=http://localhost:5209
@subscriptionId=ff09112f-6419-4ed7-9f2c-603600141f51
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF5byIsImZhbWlseV9uYW1lIjoiSFIiLCJlbWFpbCI6Im1heW9ockBtYXlvaHIuY29tIiwiaWQiOiI2Njg2NjY3YS1hMjc4LTQ3ZjUtODFjOC05Njg3NjI2MDJkNDQiLCJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImFkbWluSWQiOiI3Nzc4NTYxYS0wOWU5LTQ4YzktYjg2Mi1kNWY0MmZlYzBjYmUiLCJyb2xlcyI6WyJyYW5kb21Sb2xlIiwiQWRtaW4iXSwiZXhwIjoxNzQyMjczMjE4LCJpc3MiOiJHeW1NYW5hZ2VtZW50IiwiYXVkIjoiR3ltTWFuYWdlbWVudCJ9.pOYeK8y2FBurVULbp72v-EpZXwlZ5p29nfkMt3aoOzU

POST {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "MayoHrGym3"
}

###

http://localhost:5051/subscriptions/51b5d6fd-75fe-44d9-a56f-2dcde66fad56/gyms/59bf64b3-fee6-4403-9631-d1a4f57cb032